/* gst-client.c generated by valac, the Vala compiler
 * generated from gst-client.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <dbus/dbus-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>


#define TYPE_HARRIER_CLI (harrier_cli_get_type ())
#define HARRIER_CLI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HARRIER_CLI, HarrierCli))
#define HARRIER_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HARRIER_CLI, HarrierCliClass))
#define IS_HARRIER_CLI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HARRIER_CLI))
#define IS_HARRIER_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HARRIER_CLI))
#define HARRIER_CLI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HARRIER_CLI, HarrierCliClass))

typedef struct _HarrierCli HarrierCli;
typedef struct _HarrierCliClass HarrierCliClass;
typedef struct _HarrierCliPrivate HarrierCliPrivate;
#define _dbus_g_connection_unref0(var) ((var == NULL) ? NULL : (var = (dbus_g_connection_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))

struct _HarrierCli {
	GObject parent_instance;
	HarrierCliPrivate * priv;
};

struct _HarrierCliClass {
	GObjectClass parent_class;
};

struct _HarrierCliPrivate {
	DBusGConnection* conn;
	DBusGProxy* factory;
	char** cmds;
	gint cmds_length1;
	gint cmds_length2;
};


static char* harrier_cli_obj_path;
static char* harrier_cli_obj_path = NULL;
static gboolean harrier_cli__signals;
static gboolean harrier_cli__signals = FALSE;
static gboolean harrier_cli__debug;
static gboolean harrier_cli__debug = FALSE;
static char** harrier_cli__remaining_args;
static char** harrier_cli__remaining_args = NULL;
static gpointer harrier_cli_parent_class = NULL;

GType harrier_cli_get_type (void);
#define HARRIER_CLI_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_HARRIER_CLI, HarrierCliPrivate))
enum  {
	HARRIER_CLI_DUMMY_PROPERTY
};
HarrierCli* harrier_cli_new (GError** error);
HarrierCli* harrier_cli_construct (GType object_type, GError** error);
void harrier_cli_Error_cb (HarrierCli* self);
void harrier_cli_Eos_cb (HarrierCli* self);
void harrier_cli_StateChanged_cb (HarrierCli* self);
static char* _dynamic_CreateWithDebug0 (DBusGProxy* self, const char* param1, gboolean param2, GError** error);
static gboolean harrier_cli_pipeline_create (HarrierCli* self, const char* description);
static gboolean _dynamic_PipelinePlay1 (DBusGProxy* self, GError** error);
static gboolean harrier_cli_pipeline_play (HarrierCli* self, DBusGProxy* pipeline);
static gboolean _dynamic_PipelinePause2 (DBusGProxy* self, GError** error);
static gboolean harrier_cli_pipeline_pause (HarrierCli* self, DBusGProxy* pipeline);
static gboolean _dynamic_PipelineNull3 (DBusGProxy* self, GError** error);
static gboolean harrier_cli_pipeline_null (HarrierCli* self, DBusGProxy* pipeline);
static gint _dynamic_PipelineId4 (DBusGProxy* self, GError** error);
static gboolean _dynamic_Destroy5 (DBusGProxy* self, gint param1, GError** error);
static gboolean harrier_cli_pipeline_destroy (HarrierCli* self, DBusGProxy* pipeline);
static gboolean _dynamic_ElementGetPropertyBoolean6 (DBusGProxy* self, const char* param1, const char* param2, GError** error);
static gint _dynamic_ElementGetPropertyInt7 (DBusGProxy* self, const char* param1, const char* param2, GError** error);
static glong _dynamic_ElementGetPropertyLong8 (DBusGProxy* self, const char* param1, const char* param2, GError** error);
static char* _dynamic_ElementGetPropertyString9 (DBusGProxy* self, const char* param1, const char* param2, GError** error);
static gboolean harrier_cli_pipeline_get_property (HarrierCli* self, DBusGProxy* pipeline, char** args, int args_length1);
static gboolean _dynamic_ElementSetPropertyBoolean10 (DBusGProxy* self, const char* param1, const char* param2, gboolean param3, GError** error);
static gboolean _dynamic_ElementSetPropertyInt11 (DBusGProxy* self, const char* param1, const char* param2, gint param3, GError** error);
static gboolean _dynamic_ElementSetPropertyLong12 (DBusGProxy* self, const char* param1, const char* param2, glong param3, GError** error);
static gboolean _dynamic_ElementSetPropertyString13 (DBusGProxy* self, const char* param1, const char* param2, const char* param3, GError** error);
static gboolean harrier_cli_pipeline_set_property (HarrierCli* self, DBusGProxy* pipeline, char** args, int args_length1);
static gint _dynamic_PipelineGetDuration14 (DBusGProxy* self, GError** error);
static gboolean harrier_cli_pipeline_get_duration (HarrierCli* self, DBusGProxy* pipeline);
static gint _dynamic_PipelineGetPosition15 (DBusGProxy* self, GError** error);
static gboolean harrier_cli_pipeline_get_position (HarrierCli* self, DBusGProxy* pipeline);
static gboolean _dynamic_PipelineIsInitialized16 (DBusGProxy* self, GError** error);
static void _harrier_cli_Error_cb_dynamic_Error0_ (DBusGProxy* _sender, gpointer self);
void _dynamic_Error1_connect (gpointer obj, const char * signal_name, GCallback handler, gpointer data);
static void _harrier_cli_Eos_cb_dynamic_Eos2_ (DBusGProxy* _sender, gpointer self);
void _dynamic_Eos3_connect (gpointer obj, const char * signal_name, GCallback handler, gpointer data);
static void _harrier_cli_StateChanged_cb_dynamic_StateChanged4_ (DBusGProxy* _sender, gpointer self);
void _dynamic_StateChanged5_connect (gpointer obj, const char * signal_name, GCallback handler, gpointer data);
gboolean harrier_cli_parse_cmd (HarrierCli* self, char** args, int args_length1, GError** error);
gboolean harrier_cli_cli (HarrierCli* self, char** args, int args_length1, GError** error);
gboolean harrier_cli_parse (HarrierCli* self, char** args, int args_length1, GError** error);
static gint harrier_cli_main (char** args, int args_length1);
static void harrier_cli_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);
static int _vala_strcmp0 (const char * str1, const char * str2);

static const GOptionEntry HARRIER_CLI_options[] = {{"by_path", 'p', 0, G_OPTION_ARG_STRING, &harrier_cli_obj_path, "Pipeline path, for which command will be apply.Usage:-p <path>", NULL}, {"enable_signals", 's', 0, G_OPTION_ARG_INT, &harrier_cli__signals, "Flag to enable the signals reception.Usage:-s <1>", NULL}, {"debug", 'd', 0, G_OPTION_ARG_INT, &harrier_cli__debug, "Flag to enable debug information on a pipeline,useful just for 'create' command.Usage:-d <1>", NULL}, {"", '\0', 0, G_OPTION_ARG_FILENAME_ARRAY, &harrier_cli__remaining_args, NULL, N_ ("[COMMANDS...]")}, {NULL}};


HarrierCli* harrier_cli_construct (GType object_type, GError** error) {
	GError * _inner_error_;
	HarrierCli * self;
	DBusGConnection* _tmp0_;
	DBusGConnection* _tmp1_;
	DBusGProxy* _tmp2_;
	_inner_error_ = NULL;
	self = (HarrierCli*) g_object_new (object_type, NULL);
	_tmp0_ = dbus_g_bus_get (DBUS_BUS_SYSTEM, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return NULL;
	}
	self->priv->conn = (_tmp1_ = _tmp0_, _dbus_g_connection_unref0 (self->priv->conn), _tmp1_);
	self->priv->factory = (_tmp2_ = dbus_g_proxy_new_for_name (self->priv->conn, "com.ridgerun.gstreamer.gstd", "/com/ridgerun/gstreamer/gstd/factory", "com.ridgerun.gstreamer.gstd.FactoryInterface"), _g_object_unref0 (self->priv->factory), _tmp2_);
	return self;
}


HarrierCli* harrier_cli_new (GError** error) {
	return harrier_cli_construct (TYPE_HARRIER_CLI, error);
}


void harrier_cli_Error_cb (HarrierCli* self) {
	g_return_if_fail (self != NULL);
	fprintf (stdout, "Error signal received\n");
}


void harrier_cli_Eos_cb (HarrierCli* self) {
	g_return_if_fail (self != NULL);
	fprintf (stdout, "End of Stream signal received\n");
}


void harrier_cli_StateChanged_cb (HarrierCli* self) {
	g_return_if_fail (self != NULL);
	fprintf (stdout, "StateChanged signal received\n");
}


static char* _dynamic_CreateWithDebug0 (DBusGProxy* self, const char* param1, gboolean param2, GError** error) {
	char* result;
	dbus_g_proxy_call (self, "CreateWithDebug", error, G_TYPE_STRING, param1, G_TYPE_BOOLEAN, param2, G_TYPE_INVALID, G_TYPE_STRING, &result, G_TYPE_INVALID);
	if (*error) {
		return NULL;
	}
	return result;
}


static gboolean harrier_cli_pipeline_create (HarrierCli* self, const char* description) {
	gboolean result;
	GError * _inner_error_;
	char* new_objpath;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (description != NULL, FALSE);
	_inner_error_ = NULL;
	new_objpath = _dynamic_CreateWithDebug0 (self->priv->factory, description, harrier_cli__debug, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	if (_vala_strcmp0 (new_objpath, "") == 0) {
		fprintf (stderr, "Failed to create pipeline\n");
		result = FALSE;
		_g_free0 (new_objpath);
		return result;
	}
	fprintf (stdout, "Pipeline path created: %s\n", new_objpath);
	result = TRUE;
	_g_free0 (new_objpath);
	return result;
}


static gboolean _dynamic_PipelinePlay1 (DBusGProxy* self, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "PipelinePlay", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean harrier_cli_pipeline_play (HarrierCli* self, DBusGProxy* pipeline) {
	gboolean result;
	GError * _inner_error_;
	gboolean ret;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	ret = _dynamic_PipelinePlay1 (pipeline, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	if (!ret) {
		fprintf (stdout, "Failed to put the pipeline to play\n");
		result = FALSE;
		return result;
	}
	result = ret;
	return result;
}


static gboolean _dynamic_PipelinePause2 (DBusGProxy* self, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "PipelinePause", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean harrier_cli_pipeline_pause (HarrierCli* self, DBusGProxy* pipeline) {
	gboolean result;
	GError * _inner_error_;
	gboolean ret;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	ret = _dynamic_PipelinePause2 (pipeline, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	if (!ret) {
		fprintf (stdout, "Failed to put the pipeline to pause\n");
		result = FALSE;
		return result;
	}
	result = ret;
	return result;
}


static gboolean _dynamic_PipelineNull3 (DBusGProxy* self, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "PipelineNull", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean harrier_cli_pipeline_null (HarrierCli* self, DBusGProxy* pipeline) {
	gboolean result;
	GError * _inner_error_;
	gboolean ret;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	ret = _dynamic_PipelineNull3 (pipeline, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	if (!ret) {
		fprintf (stderr, "Failed to put the pipeline to null\n");
		result = FALSE;
		return result;
	}
	result = ret;
	return result;
}


static gint _dynamic_PipelineId4 (DBusGProxy* self, GError** error) {
	gint result;
	dbus_g_proxy_call (self, "PipelineId", error, G_TYPE_INVALID, G_TYPE_INT, &result, G_TYPE_INVALID);
	if (*error) {
		return 0;
	}
	return result;
}


static gboolean _dynamic_Destroy5 (DBusGProxy* self, gint param1, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "Destroy", error, G_TYPE_INT, param1, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean harrier_cli_pipeline_destroy (HarrierCli* self, DBusGProxy* pipeline) {
	gboolean result;
	GError * _inner_error_;
	gint id;
	gboolean ret;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	id = _dynamic_PipelineId4 (pipeline, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	ret = _dynamic_Destroy5 (self->priv->factory, id, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	if (!ret) {
		fprintf (stderr, "Failed to put the pipeline to null\n");
		result = FALSE;
		return result;
	}
	fprintf (stdout, "Pipeline with path:%s, destroyed\n", harrier_cli_obj_path);
	result = TRUE;
	return result;
}


static gboolean _dynamic_ElementGetPropertyBoolean6 (DBusGProxy* self, const char* param1, const char* param2, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "ElementGetPropertyBoolean", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gint _dynamic_ElementGetPropertyInt7 (DBusGProxy* self, const char* param1, const char* param2, GError** error) {
	gint result;
	dbus_g_proxy_call (self, "ElementGetPropertyInt", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, G_TYPE_INVALID, G_TYPE_INT, &result, G_TYPE_INVALID);
	if (*error) {
		return 0;
	}
	return result;
}


static glong _dynamic_ElementGetPropertyLong8 (DBusGProxy* self, const char* param1, const char* param2, GError** error) {
	glong result;
	dbus_g_proxy_call (self, "ElementGetPropertyLong", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, G_TYPE_INVALID, dbus_g_type_get_struct ("GValueArray", G_TYPE_INVALID), &result, G_TYPE_INVALID);
	if (*error) {
		return 0L;
	}
	return result;
}


static char* _dynamic_ElementGetPropertyString9 (DBusGProxy* self, const char* param1, const char* param2, GError** error) {
	char* result;
	dbus_g_proxy_call (self, "ElementGetPropertyString", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, G_TYPE_INVALID, G_TYPE_STRING, &result, G_TYPE_INVALID);
	if (*error) {
		return NULL;
	}
	return result;
}


static gboolean harrier_cli_pipeline_get_property (HarrierCli* self, DBusGProxy* pipeline, char** args, int args_length1) {
	gboolean result;
	GError * _inner_error_;
	gboolean ret;
	char* element;
	char* property;
	GQuark _tmp2_;
	char* _tmp1_;
	static GQuark _tmp2__label0 = 0;
	static GQuark _tmp2__label1 = 0;
	static GQuark _tmp2__label2 = 0;
	static GQuark _tmp2__label3 = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	ret = TRUE;
	element = g_strdup (args[1]);
	property = g_strdup (args[2]);
	_tmp1_ = g_utf8_strdown (args[3], -1);
	_tmp2_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	g_free (_tmp1_);
	if (_tmp2_ == ((0 != _tmp2__label0) ? _tmp2__label0 : (_tmp2__label0 = g_quark_from_static_string ("boolean"))))
	do {
		gboolean boolean_v;
		const char* _tmp0_;
		boolean_v = _dynamic_ElementGetPropertyBoolean6 (pipeline, element, property, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		_tmp0_ = NULL;
		if (boolean_v) {
			_tmp0_ = "true";
		} else {
			_tmp0_ = "false";
		}
		fprintf (stdout, ">>The '%s' value on element '%s' is: %s\n", property, element, _tmp0_);
		break;
	} while (0); else if (_tmp2_ == ((0 != _tmp2__label1) ? _tmp2__label1 : (_tmp2__label1 = g_quark_from_static_string ("integer"))))
	do {
		gint integer_v;
		integer_v = _dynamic_ElementGetPropertyInt7 (pipeline, element, property, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		fprintf (stdout, ">>The '%s' value on element '%s' is: %d\n", property, element, integer_v);
		if (integer_v == (-1)) {
			ret = FALSE;
		}
		break;
	} while (0); else if (_tmp2_ == ((0 != _tmp2__label2) ? _tmp2__label2 : (_tmp2__label2 = g_quark_from_static_string ("long"))))
	do {
		glong long_v;
		long_v = _dynamic_ElementGetPropertyLong8 (pipeline, element, property, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		fprintf (stdout, ">>The '%s' value on element '%s' is: %ld\n", property, element, long_v);
		if (long_v == (-1)) {
			ret = FALSE;
		}
		break;
	} while (0); else if (_tmp2_ == ((0 != _tmp2__label3) ? _tmp2__label3 : (_tmp2__label3 = g_quark_from_static_string ("string"))))
	do {
		char* string_v;
		string_v = _dynamic_ElementGetPropertyString9 (pipeline, element, property, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		fprintf (stdout, ">>The '%s' value on element '%s' is: %s\n", property, element, string_v);
		if (_vala_strcmp0 (string_v, "") == 0) {
			ret = FALSE;
		}
		_g_free0 (string_v);
		break;
	} while (0); else
	do {
		fprintf (stderr, "Datatype not supported: %s\n", args[4]);
		result = FALSE;
		_g_free0 (element);
		_g_free0 (property);
		return result;
	} while (0);
	if (!ret) {
		fprintf (stdout, "Failed to get property\n");
		result = FALSE;
		_g_free0 (element);
		_g_free0 (property);
		return result;
	}
	result = ret;
	_g_free0 (element);
	_g_free0 (property);
	return result;
}


static gboolean string_to_bool (const char* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	if (_vala_strcmp0 (self, "true") == 0) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}


static gboolean _dynamic_ElementSetPropertyBoolean10 (DBusGProxy* self, const char* param1, const char* param2, gboolean param3, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "ElementSetPropertyBoolean", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, G_TYPE_BOOLEAN, param3, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean _dynamic_ElementSetPropertyInt11 (DBusGProxy* self, const char* param1, const char* param2, gint param3, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "ElementSetPropertyInt", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, G_TYPE_INT, param3, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean _dynamic_ElementSetPropertyLong12 (DBusGProxy* self, const char* param1, const char* param2, glong param3, GError** error) {
	GValueArray* dbus_param3;
	gboolean result;
	dbus_param3 = g_value_array_new (0);
	dbus_g_proxy_call (self, "ElementSetPropertyLong", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, dbus_g_type_get_struct ("GValueArray", G_TYPE_INVALID), dbus_param3, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean _dynamic_ElementSetPropertyString13 (DBusGProxy* self, const char* param1, const char* param2, const char* param3, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "ElementSetPropertyString", error, G_TYPE_STRING, param1, G_TYPE_STRING, param2, G_TYPE_STRING, param3, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static gboolean harrier_cli_pipeline_set_property (HarrierCli* self, DBusGProxy* pipeline, char** args, int args_length1) {
	gboolean result;
	GError * _inner_error_;
	gboolean ret = FALSE;
	char* element;
	char* property;
	GQuark _tmp8_;
	char* _tmp7_;
	static GQuark _tmp8__label0 = 0;
	static GQuark _tmp8__label1 = 0;
	static GQuark _tmp8__label2 = 0;
	static GQuark _tmp8__label3 = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	element = g_strdup (args[1]);
	property = g_strdup (args[2]);
	_tmp7_ = g_utf8_strdown (args[3], -1);
	_tmp8_ = (NULL == _tmp7_) ? 0 : g_quark_from_string (_tmp7_);
	g_free (_tmp7_);
	if (_tmp8_ == ((0 != _tmp8__label0) ? _tmp8__label0 : (_tmp8__label0 = g_quark_from_static_string ("boolean"))))
	do {
		char* _tmp0_;
		gboolean _tmp1_;
		gboolean boolean_v;
		const char* _tmp2_;
		gboolean _tmp3_;
		boolean_v = (_tmp1_ = string_to_bool (_tmp0_ = g_utf8_strdown (args[4], -1)), _g_free0 (_tmp0_), _tmp1_);
		_tmp2_ = NULL;
		if (boolean_v) {
			_tmp2_ = "true";
		} else {
			_tmp2_ = "false";
		}
		fprintf (stdout, "Trying to set '%s' on element '%s' to %s\n", property, element, _tmp2_);
		_tmp3_ = _dynamic_ElementSetPropertyBoolean10 (pipeline, element, property, boolean_v, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		ret = _tmp3_;
		break;
	} while (0); else if (_tmp8_ == ((0 != _tmp8__label1) ? _tmp8__label1 : (_tmp8__label1 = g_quark_from_static_string ("integer"))))
	do {
		gint integer_v;
		gboolean _tmp4_;
		integer_v = atoi (args[4]);
		fprintf (stdout, "Trying to set '%s' on element '%s' to %d\n", property, element, integer_v);
		_tmp4_ = _dynamic_ElementSetPropertyInt11 (pipeline, element, property, integer_v, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		ret = _tmp4_;
		break;
	} while (0); else if (_tmp8_ == ((0 != _tmp8__label2) ? _tmp8__label2 : (_tmp8__label2 = g_quark_from_static_string ("long"))))
	do {
		glong long_v;
		gboolean _tmp5_;
		long_v = atol (args[4]);
		fprintf (stdout, "Trying to set '%s' on element '%s' to %ld\n", property, element, long_v);
		_tmp5_ = _dynamic_ElementSetPropertyLong12 (pipeline, element, property, long_v, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		ret = _tmp5_;
		break;
	} while (0); else if (_tmp8_ == ((0 != _tmp8__label3) ? _tmp8__label3 : (_tmp8__label3 = g_quark_from_static_string ("string"))))
	do {
		char* string_v;
		gboolean _tmp6_;
		string_v = g_strdup (args[4]);
		fprintf (stdout, "Trying to set '%s' on element '%s' to %s\n", property, element, string_v);
		_tmp6_ = _dynamic_ElementSetPropertyString13 (pipeline, element, property, string_v, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (string_v);
			_g_free0 (element);
			_g_free0 (property);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
		ret = _tmp6_;
		_g_free0 (string_v);
		break;
	} while (0); else
	do {
		fprintf (stderr, "Datatype not supported: %s\n", args[4]);
		result = FALSE;
		_g_free0 (element);
		_g_free0 (property);
		return result;
	} while (0);
	if (!ret) {
		fprintf (stderr, "Failed to set property\n");
		result = FALSE;
		_g_free0 (element);
		_g_free0 (property);
		return result;
	}
	result = ret;
	_g_free0 (element);
	_g_free0 (property);
	return result;
}


static gint _dynamic_PipelineGetDuration14 (DBusGProxy* self, GError** error) {
	gint result;
	dbus_g_proxy_call (self, "PipelineGetDuration", error, G_TYPE_INVALID, G_TYPE_INT, &result, G_TYPE_INVALID);
	if (*error) {
		return 0;
	}
	return result;
}


static gboolean harrier_cli_pipeline_get_duration (HarrierCli* self, DBusGProxy* pipeline) {
	gboolean result;
	GError * _inner_error_;
	gint time;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	time = _dynamic_PipelineGetDuration14 (pipeline, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	if (time < 0) {
		fprintf (stderr, "Failed to get pipeline duration\n");
		result = FALSE;
		return result;
	}
	fprintf (stdout, ">>The duration on pipeline is %d, FORMAT need to be fix \n", time);
	result = TRUE;
	return result;
}


static gint _dynamic_PipelineGetPosition15 (DBusGProxy* self, GError** error) {
	gint result;
	dbus_g_proxy_call (self, "PipelineGetPosition", error, G_TYPE_INVALID, G_TYPE_INT, &result, G_TYPE_INVALID);
	if (*error) {
		return 0;
	}
	return result;
}


static gboolean harrier_cli_pipeline_get_position (HarrierCli* self, DBusGProxy* pipeline) {
	gboolean result;
	GError * _inner_error_;
	gint pos;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (pipeline != NULL, FALSE);
	_inner_error_ = NULL;
	pos = _dynamic_PipelineGetPosition15 (pipeline, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	if (pos < 0) {
		fprintf (stderr, "Failed to get position the pipeline to null\n");
		result = FALSE;
		return result;
	}
	fprintf (stdout, ">>The position on pipeline is: %d, FORMAT need to be fix\n", pos);
	result = TRUE;
	return result;
}


static gboolean _dynamic_PipelineIsInitialized16 (DBusGProxy* self, GError** error) {
	gboolean result;
	dbus_g_proxy_call (self, "PipelineIsInitialized", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, &result, G_TYPE_INVALID);
	if (*error) {
		return FALSE;
	}
	return result;
}


static void _harrier_cli_Error_cb_dynamic_Error0_ (DBusGProxy* _sender, gpointer self) {
	harrier_cli_Error_cb (self);
}


void _dynamic_Error1_connect (gpointer obj, const char * signal_name, GCallback handler, gpointer data) {
	dbus_g_object_register_marshaller (g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, G_TYPE_INVALID);
	dbus_g_proxy_add_signal (obj, "Error", G_TYPE_INVALID);
	dbus_g_proxy_connect_signal (obj, signal_name, handler, data, NULL);
}


static void _harrier_cli_Eos_cb_dynamic_Eos2_ (DBusGProxy* _sender, gpointer self) {
	harrier_cli_Eos_cb (self);
}


void _dynamic_Eos3_connect (gpointer obj, const char * signal_name, GCallback handler, gpointer data) {
	dbus_g_object_register_marshaller (g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, G_TYPE_INVALID);
	dbus_g_proxy_add_signal (obj, "Eos", G_TYPE_INVALID);
	dbus_g_proxy_connect_signal (obj, signal_name, handler, data, NULL);
}


static void _harrier_cli_StateChanged_cb_dynamic_StateChanged4_ (DBusGProxy* _sender, gpointer self) {
	harrier_cli_StateChanged_cb (self);
}


void _dynamic_StateChanged5_connect (gpointer obj, const char * signal_name, GCallback handler, gpointer data) {
	dbus_g_object_register_marshaller (g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, G_TYPE_INVALID);
	dbus_g_proxy_add_signal (obj, "StateChanged", G_TYPE_INVALID);
	dbus_g_proxy_connect_signal (obj, signal_name, handler, data, NULL);
}


gboolean harrier_cli_parse_cmd (HarrierCli* self, char** args, int args_length1, GError** error) {
	gboolean result;
	GError * _inner_error_;
	DBusGProxy* pipeline;
	GQuark _tmp10_;
	char* _tmp9_;
	static GQuark _tmp10__label0 = 0;
	static GQuark _tmp10__label1 = 0;
	static GQuark _tmp10__label2 = 0;
	static GQuark _tmp10__label3 = 0;
	static GQuark _tmp10__label4 = 0;
	static GQuark _tmp10__label5 = 0;
	static GQuark _tmp10__label6 = 0;
	static GQuark _tmp10__label7 = 0;
	static GQuark _tmp10__label8 = 0;
	static GQuark _tmp10__label9 = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_inner_error_ = NULL;
	pipeline = NULL;
	if (harrier_cli_obj_path != NULL) {
		DBusGProxy* _tmp0_;
		pipeline = (_tmp0_ = dbus_g_proxy_new_for_name (self->priv->conn, "com.ridgerun.gstreamer.gstd", harrier_cli_obj_path, "com.ridgerun.gstreamer.gstd.PipelineInterface"), _g_object_unref0 (pipeline), _tmp0_);
		{
			gboolean ret;
			ret = _dynamic_PipelineIsInitialized16 (pipeline, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch0_g_error;
				goto __finally0;
			}
			if (!ret) {
				fprintf (stderr, "Pipeline with path:%s, was not initialiazed\n", harrier_cli_obj_path);
				result = FALSE;
				_g_object_unref0 (pipeline);
				return result;
			}
		}
		goto __finally0;
		__catch0_g_error:
		{
			GError * e;
			e = _inner_error_;
			_inner_error_ = NULL;
			{
				fprintf (stderr, "Pipeline with path:%s, has not been created\n", harrier_cli_obj_path);
				result = FALSE;
				_g_error_free0 (e);
				_g_object_unref0 (pipeline);
				return result;
			}
		}
		__finally0:
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (pipeline);
			return FALSE;
		}
	} else {
		gboolean _tmp1_ = FALSE;
		char* _tmp2_;
		gboolean _tmp3_;
		if ((_tmp3_ = _vala_strcmp0 (_tmp2_ = g_utf8_strdown (args[0], -1), "create") != 0, _g_free0 (_tmp2_), _tmp3_)) {
			char* _tmp4_;
			_tmp1_ = _vala_strcmp0 (_tmp4_ = g_utf8_strdown (args[0], -1), "help") != 0;
			_g_free0 (_tmp4_);
		} else {
			_tmp1_ = FALSE;
		}
		if (_tmp1_) {
			fprintf (stderr, "Pipeline path was not specified\n");
			result = FALSE;
			_g_object_unref0 (pipeline);
			return result;
		}
	}
	if (harrier_cli__signals) {
		gboolean _tmp5_ = FALSE;
		char* _tmp6_;
		gboolean _tmp7_;
		if ((_tmp7_ = _vala_strcmp0 (_tmp6_ = g_utf8_strdown (args[0], -1), "create") != 0, _g_free0 (_tmp6_), _tmp7_)) {
			char* _tmp8_;
			_tmp5_ = _vala_strcmp0 (_tmp8_ = g_utf8_strdown (args[0], -1), "help") != 0;
			_g_free0 (_tmp8_);
		} else {
			_tmp5_ = FALSE;
		}
		if (_tmp5_) {
			fprintf (stdout, "Signals, activated\n");
			_dynamic_Error1_connect (pipeline, "Error", (GCallback) _harrier_cli_Error_cb_dynamic_Error0_, self);
			_dynamic_Eos3_connect (pipeline, "Eos", (GCallback) _harrier_cli_Eos_cb_dynamic_Eos2_, self);
			_dynamic_StateChanged5_connect (pipeline, "StateChanged", (GCallback) _harrier_cli_StateChanged_cb_dynamic_StateChanged4_, self);
		}
	}
	_tmp9_ = g_utf8_strdown (args[0], -1);
	_tmp10_ = (NULL == _tmp9_) ? 0 : g_quark_from_string (_tmp9_);
	g_free (_tmp9_);
	if (_tmp10_ == ((0 != _tmp10__label0) ? _tmp10__label0 : (_tmp10__label0 = g_quark_from_static_string ("create"))))
	do {
		result = harrier_cli_pipeline_create (self, args[1]);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label1) ? _tmp10__label1 : (_tmp10__label1 = g_quark_from_static_string ("destroy"))))
	do {
		result = harrier_cli_pipeline_destroy (self, pipeline);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label2) ? _tmp10__label2 : (_tmp10__label2 = g_quark_from_static_string ("play"))))
	do {
		result = harrier_cli_pipeline_play (self, pipeline);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label3) ? _tmp10__label3 : (_tmp10__label3 = g_quark_from_static_string ("pause"))))
	do {
		result = harrier_cli_pipeline_pause (self, pipeline);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label4) ? _tmp10__label4 : (_tmp10__label4 = g_quark_from_static_string ("null"))))
	do {
		result = harrier_cli_pipeline_null (self, pipeline);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label5) ? _tmp10__label5 : (_tmp10__label5 = g_quark_from_static_string ("set"))))
	do {
		result = harrier_cli_pipeline_set_property (self, pipeline, args, args_length1);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label6) ? _tmp10__label6 : (_tmp10__label6 = g_quark_from_static_string ("get"))))
	do {
		result = harrier_cli_pipeline_get_property (self, pipeline, args, args_length1);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label7) ? _tmp10__label7 : (_tmp10__label7 = g_quark_from_static_string ("get-duration"))))
	do {
		result = harrier_cli_pipeline_get_duration (self, pipeline);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label8) ? _tmp10__label8 : (_tmp10__label8 = g_quark_from_static_string ("get-position"))))
	do {
		result = harrier_cli_pipeline_get_position (self, pipeline);
		_g_object_unref0 (pipeline);
		return result;
	} while (0); else if (_tmp10_ == ((0 != _tmp10__label9) ? _tmp10__label9 : (_tmp10__label9 = g_quark_from_static_string ("help"))))
	do {
		gint id;
		id = 0;
		if (args_length1 > 1) {
			while (TRUE) {
				if (!(self->priv->cmds[(id * self->priv->cmds_length2) + 0] != NULL)) {
					break;
				}
				if (_vala_strcmp0 (self->priv->cmds[(id * self->priv->cmds_length2) + 0], args[1]) == 0) {
					fprintf (stdout, "Command: %s\n", args[1]);
					fprintf (stdout, "Description: %s\n", self->priv->cmds[(id * self->priv->cmds_length2) + 2]);
					fprintf (stdout, "Syntax: %s\n", self->priv->cmds[(id * self->priv->cmds_length2) + 1]);
					result = TRUE;
					_g_object_unref0 (pipeline);
					return result;
				}
				id++;
			}
			fprintf (stdout, "Unknown command: %s\n", args[1]);
			result = FALSE;
			_g_object_unref0 (pipeline);
			return result;
		} else {
			fprintf (stdout, "%s", "Request the syntax of an specific command with " "\"help <command>\".\n" "This is the list of supported commands:\n");
			while (TRUE) {
				if (!(self->priv->cmds[(id * self->priv->cmds_length2) + 0] != NULL)) {
					break;
				}
				fprintf (stdout, " %s:\t%s\n", self->priv->cmds[(id * self->priv->cmds_length2) + 0], self->priv->cmds[(id * self->priv->cmds_length2) + 2]);
				id++;
			}
			fprintf (stdout, "\n");
		}
		break;
	} while (0); else
	do {
		fprintf (stderr, "Unkown command: %s\n", args[1]);
		result = FALSE;
		_g_object_unref0 (pipeline);
		return result;
	} while (0);
	result = TRUE;
	_g_object_unref0 (pipeline);
	return result;
}


gboolean harrier_cli_cli (HarrierCli* self, char** args, int args_length1, GError** error) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	fprintf (stdout, "CLI mode not implement yet\n");
	result = FALSE;
	return result;
}


gboolean harrier_cli_parse (HarrierCli* self, char** args, int args_length1, GError** error) {
	gboolean result;
	GError * _inner_error_;
	g_return_val_if_fail (self != NULL, FALSE);
	_inner_error_ = NULL;
	if (args_length1 > 0) {
		gboolean _tmp0_;
		_tmp0_ = harrier_cli_parse_cmd (self, args, args_length1, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return FALSE;
		}
		result = _tmp0_;
		return result;
	} else {
		gboolean _tmp1_;
		_tmp1_ = harrier_cli_cli (self, args, args_length1, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return FALSE;
		}
		result = _tmp1_;
		return result;
	}
}


static gint harrier_cli_main (char** args, int args_length1) {
	gint result;
	GError * _inner_error_;
	HarrierCli* cli;
	_inner_error_ = NULL;
	cli = NULL;
	{
		char* _tmp0_;
		GOptionContext* opt;
		HarrierCli* _tmp1_;
		HarrierCli* _tmp2_;
		gboolean _tmp3_;
		harrier_cli_obj_path = (_tmp0_ = NULL, _g_free0 (harrier_cli_obj_path), _tmp0_);
		opt = g_option_context_new ("(For Commands HELP: 'gst-client help')");
		g_option_context_set_help_enabled (opt, TRUE);
		g_option_context_add_main_entries (opt, HARRIER_CLI_options, NULL);
		g_option_context_parse (opt, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt);
			if (_inner_error_->domain == DBUS_GERROR) {
				goto __catch1_dbus_gerror;
			}
			goto __catch1_g_error;
			goto __finally1;
		}
		_tmp1_ = harrier_cli_new (&_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt);
			if (_inner_error_->domain == DBUS_GERROR) {
				goto __catch1_dbus_gerror;
			}
			goto __catch1_g_error;
			goto __finally1;
		}
		cli = (_tmp2_ = _tmp1_, _g_object_unref0 (cli), _tmp2_);
		_tmp3_ = harrier_cli_parse (cli, harrier_cli__remaining_args, _vala_array_length (harrier_cli__remaining_args), &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt);
			if (_inner_error_->domain == DBUS_GERROR) {
				goto __catch1_dbus_gerror;
			}
			goto __catch1_g_error;
			goto __finally1;
		}
		if (!_tmp3_) {
			result = -1;
			_g_option_context_free0 (opt);
			_g_object_unref0 (cli);
			return result;
		}
		_g_option_context_free0 (opt);
	}
	goto __finally1;
	__catch1_dbus_gerror:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "DBus failure: %s\n", e->message);
			result = 1;
			_g_error_free0 (e);
			_g_object_unref0 (cli);
			return result;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "Dynamic method failure\n");
			result = 1;
			_g_error_free0 (e);
			_g_object_unref0 (cli);
			return result;
		}
	}
	__finally1:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
	_g_object_unref0 (cli);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return harrier_cli_main (argv, argc);
}


static void harrier_cli_class_init (HarrierCliClass * klass) {
	harrier_cli_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HarrierCliPrivate));
	G_OBJECT_CLASS (klass)->finalize = harrier_cli_finalize;
}


static void harrier_cli_instance_init (HarrierCli * self) {
	char** _tmp0_ = NULL;
	self->priv = HARRIER_CLI_GET_PRIVATE (self);
	self->priv->cmds = (_tmp0_ = g_new0 (char*, (9 * 3) + 1), _tmp0_[0] = g_strdup ("create"), _tmp0_[1] = g_strdup ("create <\"gst-launch like pipeline description in quotes\">"), _tmp0_[2] = g_strdup ("Creates a new pipeline and returns the dbus-path to access it"), _tmp0_[3] = g_strdup ("destroy"), _tmp0_[4] = g_strdup ("-p <path> destroy"), _tmp0_[5] = g_strdup ("Destroys the pipeline specified by_path(-p)"), _tmp0_[6] = g_strdup ("play"), _tmp0_[7] = g_strdup ("-p <path> play"), _tmp0_[8] = g_strdup ("Sets the pipeline specified by_path(-p) to play state"), _tmp0_[9] = g_strdup ("pause"), _tmp0_[10] = g_strdup ("-p <path> pause"), _tmp0_[11] = g_strdup ("Sets the pipeline specified by_path(-p) to pause state"), _tmp0_[12] = g_strdup ("null"), _tmp0_[13] = g_strdup ("-p <path> null"), _tmp0_[14] = g_strdup ("Sets the pipeline specified by_path(-p) to null state"), _tmp0_[15] = g_strdup ("set"), _tmp0_[16] = g_strdup ("-p <path> set <element_name> <property_name> <data-type> <value>"), _tmp0_[17] = g_strdup ("Sets an element's property value of the pipeline(option -p needed)"), _tmp0_[18] = g_strdup ("get"), _tmp0_[19] = g_strdup ("-p <path> get <element_name> <property_name> <data_type>"), _tmp0_[20] = g_strdup ("Gets an element's property value of the pipeline(option -p needed)"), _tmp0_[21] = g_strdup ("get-duration"), _tmp0_[22] = g_strdup ("-p <path> get-duration"), _tmp0_[23] = g_strdup ("Gets the pipeline duration time(option -p needed)"), _tmp0_[24] = g_strdup ("get-position"), _tmp0_[25] = g_strdup ("-p <path> get-position"), _tmp0_[26] = g_strdup ("Gets the pipeline position(option -p needed)"), _tmp0_);
	self->priv->cmds_length1 = 9;
	self->priv->cmds_length2 = 3;
}


static void harrier_cli_finalize (GObject* obj) {
	HarrierCli * self;
	self = HARRIER_CLI (obj);
	_dbus_g_connection_unref0 (self->priv->conn);
	_g_object_unref0 (self->priv->factory);
	self->priv->cmds = (_vala_array_free (self->priv->cmds, self->priv->cmds_length1 * self->priv->cmds_length2, (GDestroyNotify) g_free), NULL);
	G_OBJECT_CLASS (harrier_cli_parent_class)->finalize (obj);
}


GType harrier_cli_get_type (void) {
	static GType harrier_cli_type_id = 0;
	if (harrier_cli_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (HarrierCliClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) harrier_cli_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HarrierCli), 0, (GInstanceInitFunc) harrier_cli_instance_init, NULL };
		harrier_cli_type_id = g_type_register_static (G_TYPE_OBJECT, "HarrierCli", &g_define_type_info, 0);
	}
	return harrier_cli_type_id;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




