/* harrierCli.c generated by valac, the Vala compiler
 * generated from harrierCli.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <dbus/dbus-glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_HARRIER_CLI (harrier_cli_get_type ())
#define HARRIER_CLI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HARRIER_CLI, HarrierCli))
#define HARRIER_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HARRIER_CLI, HarrierCliClass))
#define IS_HARRIER_CLI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HARRIER_CLI))
#define IS_HARRIER_CLI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HARRIER_CLI))
#define HARRIER_CLI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HARRIER_CLI, HarrierCliClass))

typedef struct _HarrierCli HarrierCli;
typedef struct _HarrierCliClass HarrierCliClass;
typedef struct _HarrierCliPrivate HarrierCliPrivate;
#define _dbus_g_connection_unref0(var) ((var == NULL) ? NULL : (var = (dbus_g_connection_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))

struct _HarrierCli {
	GObject parent_instance;
	HarrierCliPrivate * priv;
};

struct _HarrierCliClass {
	GObjectClass parent_class;
};

struct _HarrierCliPrivate {
	DBusGConnection* conn;
	DBusGProxy* harrier;
};


static gpointer harrier_cli_parent_class = NULL;

GType harrier_cli_get_type (void);
#define HARRIER_CLI_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_HARRIER_CLI, HarrierCliPrivate))
enum  {
	HARRIER_CLI_DUMMY_PROPERTY
};
void _dynamic_hello0 (DBusGProxy* self, GError** error);
void harrier_cli_run (HarrierCli* self, GError** error);
HarrierCli* harrier_cli_new (void);
HarrierCli* harrier_cli_construct (GType object_type);
static gint harrier_cli_main (char** args, int args_length1);
static void harrier_cli_finalize (GObject* obj);



void _dynamic_hello0 (DBusGProxy* self, GError** error) {
	dbus_g_proxy_call (self, "Hello", error, G_TYPE_INVALID, G_TYPE_INVALID);
	if (*error) {
		return;
	}
}


void harrier_cli_run (HarrierCli* self, GError** error) {
	GError * _inner_error_;
	DBusGConnection* _tmp0_;
	DBusGConnection* _tmp1_;
	DBusGProxy* _tmp2_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	_tmp0_ = dbus_g_bus_get (DBUS_BUS_SESSION, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->priv->conn = (_tmp1_ = _tmp0_, _dbus_g_connection_unref0 (self->priv->conn), _tmp1_);
	self->priv->harrier = (_tmp2_ = dbus_g_proxy_new_for_name (self->priv->conn, "com.ti.sdo.HarrierService", "/com/ti/sdo/HarrierObject", "com.ti.sdo.HarrierInterface"), _g_object_unref0 (self->priv->harrier), _tmp2_);
	fprintf (stdout, "Ready to call hello 2\n");
	_dynamic_hello0 (self->priv->harrier, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	fprintf (stdout, "Hello called\n");
}


static gint harrier_cli_main (char** args, int args_length1) {
	gint result;
	GError * _inner_error_;
	GMainLoop* loop;
	HarrierCli* test;
	_inner_error_ = NULL;
	loop = g_main_loop_new (NULL, FALSE);
	test = harrier_cli_new ();
	{
		harrier_cli_run (test, &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == DBUS_GERROR) {
				goto __catch0_dbus_gerror;
			}
			goto __catch0_g_error;
			goto __finally0;
		}
	}
	goto __finally0;
	__catch0_dbus_gerror:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "Failed to initialize");
			result = 1;
			_g_error_free0 (e);
			_g_main_loop_unref0 (loop);
			_g_object_unref0 (test);
			return result;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "Dynamic method failure");
			result = 1;
			_g_error_free0 (e);
			_g_main_loop_unref0 (loop);
			_g_object_unref0 (test);
			return result;
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_main_loop_unref0 (loop);
		_g_object_unref0 (test);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return 0;
	}
	g_main_loop_run (loop);
	result = 0;
	_g_main_loop_unref0 (loop);
	_g_object_unref0 (test);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return harrier_cli_main (argv, argc);
}


HarrierCli* harrier_cli_construct (GType object_type) {
	HarrierCli * self;
	self = (HarrierCli*) g_object_new (object_type, NULL);
	return self;
}


HarrierCli* harrier_cli_new (void) {
	return harrier_cli_construct (TYPE_HARRIER_CLI);
}


static void harrier_cli_class_init (HarrierCliClass * klass) {
	harrier_cli_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HarrierCliPrivate));
	G_OBJECT_CLASS (klass)->finalize = harrier_cli_finalize;
}


static void harrier_cli_instance_init (HarrierCli * self) {
	self->priv = HARRIER_CLI_GET_PRIVATE (self);
}


static void harrier_cli_finalize (GObject* obj) {
	HarrierCli * self;
	self = HARRIER_CLI (obj);
	_dbus_g_connection_unref0 (self->priv->conn);
	_g_object_unref0 (self->priv->harrier);
	G_OBJECT_CLASS (harrier_cli_parent_class)->finalize (obj);
}


GType harrier_cli_get_type (void) {
	static GType harrier_cli_type_id = 0;
	if (harrier_cli_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (HarrierCliClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) harrier_cli_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HarrierCli), 0, (GInstanceInitFunc) harrier_cli_instance_init, NULL };
		harrier_cli_type_id = g_type_register_static (G_TYPE_OBJECT, "HarrierCli", &g_define_type_info, 0);
	}
	return harrier_cli_type_id;
}




