/* main.c generated by valac, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gst/gst.h>
#include <stdio.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <dbus/dbus-glib.h>
#include <stdlib.h>
#include <string.h>
#include <dbus/dbus.h>

#define _dbus_g_connection_unref0(var) ((var == NULL) ? NULL : (var = (dbus_g_connection_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_HARRIER (harrier_get_type ())
#define HARRIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HARRIER, Harrier))
#define HARRIER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HARRIER, HarrierClass))
#define IS_HARRIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HARRIER))
#define IS_HARRIER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HARRIER))
#define HARRIER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HARRIER, HarrierClass))

typedef struct _Harrier Harrier;
typedef struct _HarrierClass HarrierClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
typedef struct _DBusObjectVTable _DBusObjectVTable;

struct _DBusObjectVTable {
	void (*register_object) (DBusConnection*, const char*, void*);
};



static guint _dynamic_request_name0 (DBusGProxy* self, const char* param1, guint param2, GError** error);
Harrier* harrier_new (void);
Harrier* harrier_construct (GType object_type);
GType harrier_get_type (void);
void _main (char** args, int args_length1);
static void _vala_dbus_register_object (DBusConnection* connection, const char* path, void* object);
static void _vala_dbus_unregister_object (gpointer connection, GObject* object);



static guint _dynamic_request_name0 (DBusGProxy* self, const char* param1, guint param2, GError** error) {
	guint result;
	dbus_g_proxy_call (self, "RequestName", error, G_TYPE_STRING, param1, G_TYPE_UINT, param2, G_TYPE_INVALID, G_TYPE_UINT, &result, G_TYPE_INVALID);
	if (*error) {
		return 0U;
	}
	return result;
}


void _main (char** args, int args_length1) {
	GError * _inner_error_;
	GMainLoop* loop;
	_inner_error_ = NULL;
	gst_init (&args_length1, &args);
	fprintf (stdout, "Harrier Streaming Server Daemon\n");
	loop = g_main_loop_new (NULL, FALSE);
	{
		DBusGConnection* conn;
		DBusGProxy* bus;
		guint request_name_result;
		conn = dbus_g_bus_get (DBUS_BUS_SESSION, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
			goto __finally0;
		}
		bus = dbus_g_proxy_new_for_name (conn, "org.freedesktop.DBus", "/org/freedesktop/DBus", "org.freedesktop.DBus");
		request_name_result = _dynamic_request_name0 (bus, "com.ti.sdo.HarrierService", (guint) 0, &_inner_error_);
		if (_inner_error_ != NULL) {
			_dbus_g_connection_unref0 (conn);
			_g_object_unref0 (bus);
			goto __catch0_g_error;
			goto __finally0;
		}
		if (request_name_result == DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER) {
			Harrier* hawk;
			hawk = harrier_new ();
			_vala_dbus_register_object (dbus_g_connection_get_connection (conn), "/com/ti/sdo/HarrierObject", (GObject*) hawk);
			fprintf (stdout, "Listening for connections...\n");
			g_main_loop_run (loop);
			_g_object_unref0 (hawk);
		} else {
			fprintf (stderr, "Failed to obtain primary ownership of the service\n");
			fprintf (stderr, "%s", "This usually means there is another instance of " "harrier already running\n");
		}
		_dbus_g_connection_unref0 (conn);
		_g_object_unref0 (bus);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "Oops: %s\n", e->message);
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_main_loop_unref0 (loop);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_main_loop_unref0 (loop);
}


int main (int argc, char ** argv) {
	g_type_init ();
	_main (argv, argc);
	return 0;
}


static void _vala_dbus_register_object (DBusConnection* connection, const char* path, void* object) {
	const _DBusObjectVTable * vtable;
	vtable = g_type_get_qdata (G_TYPE_FROM_INSTANCE (object), g_quark_from_static_string ("DBusObjectVTable"));
	if (vtable) {
		vtable->register_object (connection, path, object);
	} else {
		g_warning ("Object does not implement any D-Bus interface");
	}
}


static void _vala_dbus_unregister_object (gpointer connection, GObject* object) {
	char* path;
	path = g_object_steal_data ((GObject*) object, "dbus_object_path");
	dbus_connection_unregister_object_path (connection, path);
	g_free (path);
}




