/* main.c generated by valac 0.14.0, the Vala compiler
 * generated from main.vala, do not modify */

/*
 * gstd/src/main.vala
 *
 * Main function for GStreamer daemon - framework for controlling audio and video streaming using D-Bus messages
 *
 * Copyright (c) 2010, RidgeRun
 * All rights reserved.
 *
 * GPL2 license - See http://www.opensource.org/licenses/gpl-2.0.php for complete text.
 */
/*Global Variable*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <syslog.h>
#include <gst/gst.h>


#define TYPE_GSTD_SIGNALS (gstd_signals_get_type ())
#define GSTD_SIGNALS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GSTD_SIGNALS, GstdSignals))
#define GSTD_SIGNALS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GSTD_SIGNALS, GstdSignalsClass))
#define IS_GSTD_SIGNALS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GSTD_SIGNALS))
#define IS_GSTD_SIGNALS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GSTD_SIGNALS))
#define GSTD_SIGNALS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GSTD_SIGNALS, GstdSignalsClass))

typedef struct _GstdSignals GstdSignals;
typedef struct _GstdSignalsClass GstdSignalsClass;

#define TYPE_FACTORY (factory_get_type ())
#define FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FACTORY, Factory))
#define FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FACTORY, FactoryClass))
#define IS_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FACTORY))
#define IS_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FACTORY))
#define FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FACTORY, FactoryClass))

typedef struct _Factory Factory;
typedef struct _FactoryClass FactoryClass;
typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

typedef enum  {
	ERROR_GSTD_OPTION,
	ERROR_GSTD_BUS,
	ERROR_GSTD_SERVICE_OWNERSHIP
} ErrorGstd;
#define ERROR_GSTD error_gstd_quark ()
struct _Block1Data {
	int _ref_count_;
	GMainLoop* loop;
	Factory* factory;
};


extern gboolean useSystemBus;
gboolean useSystemBus = FALSE;
extern gboolean useSessionBus;
gboolean useSessionBus = FALSE;
extern gint debugLevel;
gint debugLevel = 0;
extern gint signalPollRate;
gint signalPollRate = 0;

GQuark error_gstd_quark (void);
gint _vala_main (gchar** args, int args_length1);
GType gstd_signals_get_type (void) G_GNUC_CONST;
GType factory_get_type (void) G_GNUC_CONST;
guint factory_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (Block1Data* _data1_);
GstdSignals* gstd_signals_new (void);
GstdSignals* gstd_signals_construct (GType object_type);
Factory* factory_new (GDBusConnection* conn);
Factory* factory_construct (GType object_type, GDBusConnection* conn);
static void ___lambda0_ (Block1Data* _data1_, GDBusConnection* connection, const gchar* name);
static void ____lambda0__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self);
static void ___lambda1_ (Block1Data* _data1_, GDBusConnection* connection, const gchar* name);
static void ____lambda1__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self);
void gstd_signals_monitor (GstdSignals* self, GMainLoop* loop, Factory* factory, guint pollrate_ms);

const GOptionEntry options[4] = {{"system", '\0', 0, G_OPTION_ARG_NONE, &useSystemBus, "Use system bus", NULL}, {"session", '\0', 0, G_OPTION_ARG_NONE, &useSessionBus, "Use session bus", NULL}, {"debug", 'd', 0, G_OPTION_ARG_INT, &debugLevel, "Set debug level (0..3: error, warning, info, debug)", NULL}, {NULL}};

GQuark error_gstd_quark (void) {
	return g_quark_from_static_string ("error_gstd-quark");
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (Block1Data* _data1_) {
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_object_unref0 (_data1_->factory);
		_g_main_loop_unref0 (_data1_->loop);
		g_slice_free (Block1Data, _data1_);
	}
}


static void ___lambda0_ (Block1Data* _data1_, GDBusConnection* connection, const gchar* name) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (connection != NULL);
	g_return_if_fail (name != NULL);
	{
		GDBusConnection* _tmp0_;
		Factory* _tmp1_;
		_tmp0_ = connection;
		_tmp1_ = _data1_->factory;
		factory_register_object (_tmp1_, _tmp0_, "/com/ridgerun/gstreamer/gstd/factory", &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_IO_ERROR) {
				goto __catch2_g_io_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally2;
	__catch2_g_io_error:
	{
		GError* e = NULL;
		GMainLoop* _tmp2_;
		e = _inner_error_;
		_inner_error_ = NULL;
		syslog (LOG_ERR, "Could not register service", NULL);
		_tmp2_ = _data1_->loop;
		g_main_loop_quit (_tmp2_);
		_g_error_free0 (e);
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void ____lambda0__gbus_name_acquired_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	___lambda0_ (self, connection, name);
}


static void ___lambda1_ (Block1Data* _data1_, GDBusConnection* connection, const gchar* name) {
	GMainLoop* _tmp0_;
	g_return_if_fail (connection != NULL);
	g_return_if_fail (name != NULL);
	syslog (LOG_ERR, "Lost bus name", NULL);
	_tmp0_ = _data1_->loop;
	g_main_loop_quit (_tmp0_);
}


static void ____lambda1__gbus_name_lost_callback (GDBusConnection* connection, const gchar* name, gpointer self) {
	___lambda1_ (self, connection, name);
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GstdSignals* signal_processor;
	GError * _inner_error_ = NULL;
	signal_processor = NULL;
	{
		Block1Data* _data1_;
		GOptionContext* _tmp0_;
		GOptionContext* opt;
		GOptionContext* _tmp1_;
		gint _tmp6_;
		gint _tmp11_;
		gboolean _tmp13_ = FALSE;
		gboolean _tmp14_;
		gboolean _tmp16_;
		GMainLoop* _tmp18_;
		GBusType _tmp19_ = 0;
		gboolean _tmp20_;
		GBusType _tmp24_;
		GDBusConnection* _tmp25_ = NULL;
		GDBusConnection* connection;
		GDBusConnection* _tmp26_;
		Factory* _tmp27_;
		GDBusConnection* _tmp28_;
		GstdSignals* _tmp29_;
		GMainLoop* _tmp34_;
		_data1_ = g_slice_new0 (Block1Data);
		_data1_->_ref_count_ = 1;
		openlog ("gstd", LOG_PID, LOG_USER);
		syslog (LOG_ERR, "Started", NULL);
		_tmp0_ = g_option_context_new ("");
		opt = _tmp0_;
		_tmp1_ = opt;
		g_option_context_add_main_entries (_tmp1_, options, NULL);
		{
			GOptionContext* _tmp2_;
			_tmp2_ = opt;
			g_option_context_parse (_tmp2_, &args_length1, &args, &_inner_error_);
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_OPTION_ERROR) {
					goto __catch1_g_option_error;
				}
				_g_option_context_free0 (opt);
				block1_data_unref (_data1_);
				_data1_ = NULL;
				_g_object_unref0 (signal_processor);
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return 0;
			}
		}
		goto __finally1;
		__catch1_g_option_error:
		{
			GError* e = NULL;
			GError* _tmp3_;
			const gchar* _tmp4_;
			GError* _tmp5_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp3_ = e;
			_tmp4_ = _tmp3_->message;
			_tmp5_ = g_error_new (ERROR_GSTD, ERROR_GSTD_OPTION, "OptionError failure: %s", _tmp4_);
			_inner_error_ = _tmp5_;
			_g_error_free0 (e);
			goto __finally1;
		}
		__finally1:
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt);
			block1_data_unref (_data1_);
			_data1_ = NULL;
			goto __catch0_g_error;
		}
		_tmp6_ = debugLevel;
		switch (_tmp6_) {
			case 0:
			{
				gint _tmp7_ = 0;
				_tmp7_ = LOG_UPTO (LOG_ERR);
				setlogmask (_tmp7_);
				break;
			}
			case 1:
			{
				gint _tmp8_ = 0;
				_tmp8_ = LOG_UPTO (LOG_WARNING);
				setlogmask (_tmp8_);
				break;
			}
			case 2:
			{
				gint _tmp9_ = 0;
				_tmp9_ = LOG_UPTO (LOG_INFO);
				setlogmask (_tmp9_);
				break;
			}
			default:
			{
				gint _tmp10_ = 0;
				_tmp10_ = LOG_UPTO (LOG_DEBUG);
				setlogmask (_tmp10_);
				break;
			}
		}
		syslog (LOG_DEBUG, "Debug logging enabled", NULL);
		_tmp11_ = signalPollRate;
		if (_tmp11_ > 0) {
			GstdSignals* _tmp12_;
			_tmp12_ = gstd_signals_new ();
			_g_object_unref0 (signal_processor);
			signal_processor = _tmp12_;
		}
		_tmp14_ = useSystemBus;
		if (_tmp14_) {
			gboolean _tmp15_;
			_tmp15_ = useSessionBus;
			_tmp13_ = _tmp15_;
		} else {
			_tmp13_ = FALSE;
		}
		_tmp16_ = _tmp13_;
		if (_tmp16_) {
			GError* _tmp17_;
			_tmp17_ = g_error_new_literal (ERROR_GSTD, ERROR_GSTD_BUS, "you have to choose: system or session bus");
			_inner_error_ = _tmp17_;
			_g_option_context_free0 (opt);
			block1_data_unref (_data1_);
			_data1_ = NULL;
			goto __catch0_g_error;
		}
		gst_init (&args_length1, &args);
		_tmp18_ = g_main_loop_new (NULL, FALSE);
		_data1_->loop = _tmp18_;
		_tmp20_ = useSystemBus;
		if (_tmp20_) {
			_tmp19_ = G_BUS_TYPE_SYSTEM;
		} else {
			GBusType _tmp21_ = 0;
			gboolean _tmp22_;
			GBusType _tmp23_;
			_tmp22_ = useSessionBus;
			if (_tmp22_) {
				_tmp21_ = G_BUS_TYPE_SESSION;
			} else {
				_tmp21_ = G_BUS_TYPE_STARTER;
			}
			_tmp23_ = _tmp21_;
			_tmp19_ = _tmp23_;
		}
		_tmp24_ = _tmp19_;
		_tmp25_ = g_bus_get_sync (_tmp24_, NULL, &_inner_error_);
		connection = _tmp25_;
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt);
			block1_data_unref (_data1_);
			_data1_ = NULL;
			goto __catch0_g_error;
		}
		_tmp26_ = connection;
		_tmp27_ = factory_new (_tmp26_);
		_data1_->factory = _tmp27_;
		_tmp28_ = connection;
		g_bus_own_name_on_connection_with_closures (_tmp28_, "com.ridgerun.gstreamer.gstd", G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) ((____lambda0__gbus_name_acquired_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ____lambda0__gbus_name_acquired_callback, block1_data_ref (_data1_), block1_data_unref)), (GClosure*) ((____lambda1__gbus_name_lost_callback == NULL) ? NULL : g_cclosure_new ((GCallback) ____lambda1__gbus_name_lost_callback, block1_data_ref (_data1_), block1_data_unref)));
		_tmp29_ = signal_processor;
		if (_tmp29_ != NULL) {
			GstdSignals* _tmp30_;
			GMainLoop* _tmp31_;
			Factory* _tmp32_;
			gint _tmp33_;
			_tmp30_ = signal_processor;
			_tmp31_ = _data1_->loop;
			_tmp32_ = _data1_->factory;
			_tmp33_ = signalPollRate;
			gstd_signals_monitor (_tmp30_, _tmp31_, _tmp32_, (guint) _tmp33_);
		}
		_tmp34_ = _data1_->loop;
		g_main_loop_run (_tmp34_);
		_g_object_unref0 (connection);
		_g_option_context_free0 (opt);
		block1_data_unref (_data1_);
		_data1_ = NULL;
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp35_;
		const gchar* _tmp36_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp35_ = e;
		_tmp36_ = _tmp35_->message;
		syslog (LOG_ERR, "Error: %s", _tmp36_, NULL);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (signal_processor);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	syslog (LOG_ERR, "Ended", NULL);
	result = 0;
	_g_object_unref0 (signal_processor);
	return result;
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	return _vala_main (argv, argc);
}



